baseurl = "http://www.example.com"
title = "Joe Smith"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Joseph Smith"
  info = "Graduate software engineer from the University of Lincoln"
  description = ""
  keywords = "blog,developer,personal"
  avatarurl = "img/pfp.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/TheAverageJoe01"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = ""
[[params.social]]
  name = "Email"
  icon = "fa fa-at fa-2x"
  weight = 3
  url = "mailto:joesmithdev@gmail.com"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url  = "about/"
[[menu.main]]
  name = "Resume"
  pageref = "resume"
  weight = 2
  url = "/CV.pdf"
